### ISSUE TITLE
Version 12.2 loads this DWG much worse compared to v12.1

### ISSUE THREAD

**Issue by timoria21** [LibreDWG/libredwg#326]
Hello,

Trying the attached DWG file with the latest build we get a much worse result. Screenshots are included in the attached zip file.

[TestDWG.zip](https://github.com/LibreDWG/libredwg/files/6081593/TestDWG.zip)

**Comment by rurban** [comment]
Yes, should be fixed with 8e665f0273de973cbf2c804d999be5d0f788737d

More bitsize and size recalculations are needed with DD types, if missing leading to wrong hdl offsets.

**Comment by rurban** [comment]
Nope, still wrong sizes

**Comment by rurban** [comment]
with 0.12.1 we got 59996 rewrite errors with this testcase.
with 14527d3eed139a23a6cd165ed591be8337ad18ba we get 187 errors.
with 7d4210cff1d34d226b8eacd4e4b06a418ef14a54 we get 63 errors.

**Comment by rurban** [comment]
what is remaining is a wrong scale DD encode for scale.z 3 vs 0

**Comment by timoria21** [comment]
I tried to build and run libredwg-0.12.3.4231-win64 but the issue is still there (see attached files). 
![Result 12 3](https://user-images.githubusercontent.com/79898585/111759644-1bf23300-889e-11eb-9f61-bc5a3cb4b2ab.png)
[TestDWG_12.3.zip](https://github.com/LibreDWG/libredwg/files/6170069/TestDWG_12.3.zip)


What am I missing?

**Comment by rurban** [comment]
Thanks for the recovery log. Looks like the BLOCK "1573" is broken, and more. 
I suspect BLOCK subentity and POLYLINE vertex ordering a bit broken...

**Comment by timoria21** [comment]
Hello, any news on this topic?

**Comment by rurban** [comment]
Yes, see above. Not repro
